softdevteam/warmup_stats

- bin/table_classification_summaries_others
- bin/warmup_stats
- warmup/latex.py
- warmup/summary_statistics.py
LaTeX output before this PR: [long_before.pdf](https://github.com/softdevteam/warmup_stats/files/1376385/long_before.pdf)
and after: [long_after.pdf](https://github.com/softdevteam/warmup_stats/files/1376396/long_after.pdf)
> Optionally use longtable for LaTeX tables.

- build.sh
This is certainly not a complete list, but I noticed earlier that if these things are missing, then installation fails in weird or silent fashion (e.g. it appears to continue successfully, but doesn't install things, and scrolling back through the terminal one eventually spots the source of the error). It would be good to think more carefully about what other things are needed, but this is a
start at least.
> Check for (some) packages needed for installation to complete.

- .gitignore
- build.sh
Switch to using devtools::install_git instead of devtools::install_github for the changepoint r module.
Added a gitignore for all compiled python filed generated and the work directories contents
> More windows/WSL fixes

- warmup/latex.py
This fixes a bug where table headings appeared in the wrong place, with a duplicate horizontal rule beneath them.
Example (note, both pages of the PDF are important here!):
**Before:** [before_table_before.pdf](https://github.com/softdevteam/warmup_stats/files/1644483/before_table_before.pdf)
**After:** [before_table_after.pdf](https://github.com/softdevteam/warmup_stats/files/1644484/before_table_after.pdf)
Fixes #15
> Correctly space table headings.

- bin/diff_results
- warmup/latex.py
- warmup/summary_statistics.py
This PR adds a script which allows the user to diff two Krun results files, based on the algorithm that generated Figures 9 / 11 in the warmup paper.
The output is a LaTeX table, similar to the one produced by `table_classification_summaries_others`, which shows the results of the *second* input file, and some extra symbols showing which parts of the table have improved / worsened, etc. 
The symbol next to the benchmark name shows the 'intersection' of the other measures for that benchmark. Where NSS's appear in the summaries, we sometimes cannot compare before/after results, or sometimes we can only say that the two results differ.
The script dumps a human-readable JSON file with the results of the summary and the diff. This JSON file can then be read in by the script to produce a LaTeX …
> Diff Krun results files

- bin/warmup_stats
Example with debug output (using the Linux 2 / 3 data from the full experiment, which I am pretending came from the same machine:
```
$ ./bin/warmup_stats --output-diff warmup_diff.tex octane_v8_results_0_8_linux2_i7_4790.csv octane_v8_results_0_8_linux3_e3_1240.csv -l javascript --vm Octane --uname "`uname -a`" --debug INFO
[2018-01-31 10:00:00: INFO] Checking environment.
[2018-01-31 10:00:00: INFO] Converting CSV to Krun JSON format.
[2018-01-31 10:00:00: INFO] Checking input files.
[2018-01-31 10:00:00: INFO] Converting CSV to Krun JSON.
[2018-01-31 10:00:02: INFO] Writing out: octane_v8_results_0_8_linux2_i7_4790.json.bz2
[2018-01-31 10:00:07: INFO] Writing out: octane_v8_results_0_8_linux3_e3_1240.json.bz2
[2018-01-31 10:00:07: INFO] Marking outliers in JSON.
[2018-01-31 10:00:38: …
```
> Add diff_results to warmup_stats

- bin/diff_results
Needs squashing.
New algorithm:
* If all CIs overlap, classifications are the SAME
* Otherwise:
* If the "after" results have strictly more warmups+flats than the "before" results, we say they are BETTER
* If the "after" results have more slowdown+NSS than the "before" results we say they are WORSE
* If the ONLY difference between "before" and "after" results is in the number of warmups and flats, we say they are the SAME
* Otherwise we say they are DIFFERENT 
Example case:
* Master branch: [tom2_before_fix.pdf](https://github.com/softdevteam/warmup_stats/files/1689899/tom2_before_fix.pdf)
* This branch: [tom2.pdf](https://github.com/softdevteam/warmup_stats/files/1689901/tom2.pdf)
> Improve the diff between classifications

- warmup/latex.py
Works in both "normal" and diff tables.
This seems like such an odd and brittle fix that I feel very uncomfortable about it. However, it works on the CSV files I tested with `--output-table` and `--output-diff`.
Fixes #15
> Fix longtable headings.

- README.md
- bin/diff_results
- bin/warmup_stats
- warmup/html.py
- warmup/summary_statistics.py
**PLEASE DO NOT MERGE JUST YET**
This is the first (of two) PRs to address Issue #18 (the second PR will add histograms). This PR adds HTML diff tables, which are coloured similarly to the PDF tables. Currently deltas are missing, and the README needs updating.
Example PDF file: [tom2.pdf](https://github.com/softdevteam/warmup_stats/files/1711833/tom2.pdf)
Equivalent HTML:
This PR significantly changes the CLI options for `warmup_stats` and `diff_result`, which will affect end users:
```sh
$ ./bin/warmup_stats --help
usage: warmup_stats [-h] [--debug DEBUG_LEVEL] --language LANGUAGE --vm VM
--uname UNAME (--html | --tex)
[--output-plots PDF_FILENAME]
[--output-table TABLE_FILENAME]
[--output-json JSON_FILENAME]
[--output-diff DIFF_FILENAME]
csv_files [csv_files ...]
Analyse CSV results …
```
> Html diff tables

- warmup/html.py
- warmup/summary_statistics.py
This adds a `<br/>` to longer classifications, just to make sizing the table a bit more intuitive in smaller screens.
> Tweak whitespace in HTML tables.

- README.md
- bin/warmup_stats
Fixes #13 
User now only needs to specify -l, -v and -u with CSV files.
README updated to match script.
This also enables us to create HTML results / diff tables from Krun results files.
Tested by creating diffs for both CSV and Krun files. Example debug output:
```
$ ./bin/warmup_stats --debug DEBUG --output-diff diff.html --html test-krun/before_results.json.bz2 test-krun/after_results.json.bz2 
[2018-02-15 16:13:21: DEBUG] warmup_stats script starting...
[2018-02-15 16:13:21: DEBUG] arguments: --debug DEBUG --output-diff diff.html --html test-krun/before_results.json.bz2 test-krun/after_results.json.bz2
[2018-02-15 16:13:21: INFO] Checking sanity of CLI options.
[2018-02-15 16:13:21: INFO] Checking environment.
[2018-02-15 16:13:21: INFO] Processing input files, converting to Krun JSON …
```
> warmup_stats can take Krun JSON files as input.

- bin/plot_krun_results
- bin/warmup_stats
This fixes a bug (Issue #43) where VM instrumentation data could not be drawn with changepoints or outliers, due to the way we were guessing the name of the directory containing the instrumentation
data.
In the new code, we look for all files or directories named `*_instr_data`, filter out any that are not directories, and filter out any that do not have a prefix common to the filename of the benchmarking data. i.e. if the input filename is: `warmup_outliers_w200_changepoints.json.bz2` then we would accept directores such as `warmup_instr_data/` or `warmup_whatever_instr_data/`
If there is more than one candidate directory, we issue a warning to the user and pick one at random.
Example (with outliers): 
[test_issue43.pdf](https://github.com/softdevteam/warmup_stats/files/1928459/test_issue …
> Collect instrumentation data from correct dir.

- bin/warmup_stats
This fixes a bug where the \hline under table headings was
too short for the table width.
> Run pdflatex twice.

- bin/table_classification_summaries_others
- bin/warmup_stats
- warmup/summary_statistics.py
Please see individual commit messages.
Fixes #52 which discovered that LaTeX tables could sometimes exceed the `\textwidth` if `longtable` is used with `--num-splits > 1`.
(Assigning @ltratt because this affects CLI options relevant to both warmup and the other projects)
> Fix issue 52

- bin/diff_results
- warmup/latex.py
- warmup/summary_statistics.py
Fixes #54 
This turns out to be two bugs, so it needs two test cases...
Diff table before (pp2 better example than pp1): [old-diff.pdf](https://github.com/softdevteam/warmup_stats/files/1971285/old-diff.pdf)
Diff table after: [new-diff.pdf](https://github.com/softdevteam/warmup_stats/files/1971287/new-diff.pdf)
Normal table before: [old-table.pdf](https://github.com/softdevteam/warmup_stats/files/1971276/old-table.pdf)
Normal table after: [new-table.pdf](https://github.com/softdevteam/warmup_stats/files/1971279/new-table.pdf)
> Fix issue 54

- bin/plot_krun_results
- warmup/plotting.py
This is a first go at better y-labels for instrumentation plots, here we apply word-wrapping. This may not be the best solution, but it avoids having a new CLI option.
I don't have great test data for this, so it would be helpful if someone else can give it a kicking. 
Fixes #50
> Improve y-labels on instrumentation plots.

- bin/diff_results
This fixes a bug which prevented error messages from being reported to the user.
> Fix typo in CLI parser.

- bin/plot_krun_results
These used to plot the rolling median and Tukey window, which
was only used for debugging the plotting and stats code.
Fixes #73
> Remove -m and -t from plot script.

- bin/plot_krun_results
Fix issue #35 by removing plot legends altogether. We have not used these for a very long time, and they were always quite buggy.
> Remove legends from plots.

- INSTALL.md
- build.sh
This is not needed by the bin/ scripts, but the build script uses it to determine the Debian version (in order to pass correct CLI arguments to pip).
Fixes #77
> Do not build if lsb_release is not installed.

- bin/diff_results
Sometimes the steady iter data of a vm/benchmark pair will have no variation, leading to a divide by zero in the diffing code. This commit fixes that by checking for this special case.
We also remove some code duplication.
> Fix a divide by zero.

- warmup/summary_statistics.py
This crash was caused by an if statement which did not correctly check whether a diff table had been requested by the calling function. When an "ordinary" results table was required and diff information was not available an assertion error was raised.
> Fix crash in LaTeX tables.

- bin/diff_results
- warmup/latex.py
- warmup/summary_statistics.py
This package allows us to colour individual table cells, and (unlike our own attempts to do this) correctly sizes each cell. This makes diff tables considerably neater and easier to read.
In addition, the resulting code is much simpler.
Master branch: [why_green_master.pdf](https://github.com/softdevteam/warmup_stats/files/2388441/why_green_master.pdf)
Feature branch: [why_green_better.pdf](https://github.com/softdevteam/warmup_stats/files/2388438/why_green_better.pdf)
Fixes #83
> Use colortbl for coloured LaTeX tables.

- bin/diff_results
- bin/plot_krun_results
- bin/warmup_stats
- warmup/summary_statistics.py
By default, the stats differ assumes that the user is working on one VM, and wishes to diff its benchmark results to determine whether a recent change in the VM has resulted in an improvement.
This PR adds another use case: where the user wishes to diff one VM against another. We cheat slightly, by simply renaming both VMs to the text we wish to see on the page `VM1 vs. VM2`.
Fixes #71 
In addition, since we're messing with CLI options, I've tidied (i.e. improved whitespace) the CLI options in the plotting script.
It's probably worth adding that Issue #89 is related to this one -- i.e. if the user diffs one VM against another, but one VM skipped a benchmark that the other executed, the diff script currently crashes. A later PR will fix this.
> Allow users to diff two VMs

- bin/diff_results
- warmup/summary_statistics.py
When the user wishes to diff one VM against another, sometimes a benchmark has been skipped by one VM but not by the other VM. In this case, we do not attempt to write anything into the diff table for the skipped benchmark.
There is an old dataset where the `GC64` benchmark skipped `capnproto_decode` which can be used to tet this. It works on my laptop.
Fixes #89
> Differ ignores skipped benchmarks.

- bin/diff_results
- warmup/html.py
- warmup/summary_statistics.py
In some cases we have CIs narrowing by 0.000012s which is hard to justify. This diff sets a minimum threshold of 0.001s as being considered significant (this deliberately mirrors the threshold used to determine if two changepoint segments are correct).
Tom: this is untested. Can you try it on (at least) the LuaJIT vs. counters HTML diff and see if it does the right thing? Thanks!
> Only say that CIs have narrowed if it exceeds a certain threshold.

- warmup/summary_statistics.py
Sometimes "skipped" can be None, so check for that accordingly. Should fix #93.
@fsfod can you check that a) this fixes your immediate bug b) doesn't make your other major use cases break? This isn't part of the code I'm very familiar with, so it's a bit difficult to know if I've broken something that isn't the use case I'm trying.
> Fix a bug introduced in b0739a5

- warmup/bootstrapper.py
This slightly improves performance from "insanely unusable" to "it's so slow, I still won't bother".
In numbers, a 760s task runs now in 230s.
> Speedup bootstrapping

- bin/warmup_stats
- warmup/bootstrapper.py
- warmup/statistics.py
- warmup/summary_statistics.py
PR #97 showed that we can get meaningful performance changes in table generation if we're prepared to tolerate slightly lower quality stats. In that PR, I made a rough estimate of how inaccurate they might be. However, I neglected to consider that floating point numbers have a very uneven spread: 50% of FP numbers reside between 0 and 1. In other words, the error is going to increase as someone's benchmark timings increase, which is surprising.
This commit introduces a --quality option with two settings: "low" (and fast) and "high" (and slow). The default is "high". Relative to #97, "low" also reduces the bootstrapping iterations, as well as using less accurate floating point summing. Roughly speaking, "high" is about 3x slower than "low", but one can observe small changes (at the fifth …
> Add a --quality switch to warmup_stats.

- .travis.yml
- bin/mark_changepoints_in_json
- warmup/statistics.py
- warmup/summary_statistics.py
This is my first attempt at relative deltas in warmup stats.
We add the ability to pass `--delta X%`, where the delta is X% of the *fastest* segment.
This is not a codebase I am familiar with, so please check carefully.
I found two places where we have to compute the absolute delta.
For now this is a draft PR.
> First stab at relative delta functionality.

- README.md
Since the example is about producing plots, I think `--output-json` was left in by mistake.
Fixes https://github.com/softdevteam/warmup_stats/issues/107.
> `--output-plots` can't be specified with `--output-json`.
